### ISSUE TITLE
Point at stable dependencies instead of dev-master

### ISSUE THREAD

**Issue by ewinslow** [Elgg/starter-project#11]
Want 2.0.0+ versions of core and plugins if possible.

**Comment by mrclay** [comment]
We also need a mechanism to auto-tag the plugin repos in sync with Elgg.

**Comment by ewinslow** [comment]
I don't think they need to be in sync with Elgg after 2.0.0, do they?

**Comment by mrclay** [comment]
If 2.0.1 fixes several bugs in a few plugins, shouldn't upgrading starter-project get those fixes?

**Comment by ewinslow** [comment]
Sorry, I was assuming we'd develop the plugins independently. So contributions to core wouldn't affect plugins. We'd patch and tag plugins separately (again, like every other plugin developer does). But this has not been decided for certain. No one else seems interested in this besides me :)

I don't know if the current approach of pushing from core to another repo will work with branches .

**Comment by ewinslow** [comment]
We are not going to develop core plugins independently for now, instead preferring to copy them from elgg/elgg after a `composer update` or `install`.

The exception is perhaps external plugins that we're pulling in via composer already like login_as.
