### ISSUE TITLE
How to use something like bower to manage frontend libs?

### ISSUE THREAD

**Issue by Srokap** [Elgg/starter-project#2]
One approach could be to copy package.json on install and run `bower install`. Would we like to assume that user takes control over frontend assets by customizing package.json in his project? How to make sure that Elgg necessary assets are included? How to not mess things up on update?

**Comment by ewinslow** [comment]
I think we assume that static assets are actually checked in to the source and already configured to be served via simplecache

**Comment by ewinslow** [comment]
(I.e. same situation as now when sharing static assets between plugins).

**Comment by ewinslow** [comment]
https://github.com/francoispluchino/composer-asset-plugin

**Comment by ewinslow** [comment]
composer-asset-plugin is now used by core. It certainly makes sense to use it here too.
