### ISSUE TITLE
Allow folks to use the root directory to make local modifications

### ISSUE THREAD

**Issue by ewinslow** [Elgg/starter-project#7]
This should work as if it were the last plugin loaded, so:
- views directory overrides all other views
- start.php runs last

**Comment by mrclay** [comment]
Would prefer to allow registering an arbitrary directory as a plugin, even if it only works as the "last one" in the short term.

**Comment by ewinslow** [comment]
Sounds good. Plugins are tied to entities right now. I wonder how much effort it will take to tease those things apart.

**Comment by ewinslow** [comment]
This is done in the composer-dependency branch of ewinslow/elgg. I'm fairly certain this will be a game-changer for rapid development of custom sites with Elgg if we can pull it off right...

**Comment by ewinslow** [comment]
Done! Woohoo!
